version: '3.3'

services:
  lab4-db-node-1:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: lab4-db-node-1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - arch-network
    ports:
      - 3360:3306
    volumes:
      - lab4-db-node-1-data:/var/lib/mysql
      - ./database_init/init_shard_0/init.sql:/docker-entrypoint-initdb.d/init.sql

  lab4-db-node-2:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: lab4-db-node-2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - arch-network
    ports:
      - 3361:3306
    volumes:
      - lab4-db-node-2-data:/var/lib/mysql
      - ./database_init/init_shard_1/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    networks:
      - arch-network
    volumes: 
      - lab4-cache:/data
  
  proxysql:
    build:
      context: ./proxysql
      dockerfile: Dockerfile
    container_name: proxysql
    command: >
      --initial
    volumes:
      - lab4-proxysql-data:/var/lib/proxysql
    healthcheck:
      test: "/usr/bin/mysql --user=stud --password=stud --execute \"SHOW DATABASES;\""
      interval: 15s
      timeout: 20s
      retries: 5
    networks:
      - arch-network
    ports:
      # Mysql Client Port
      - "6033:6033"
      # Mysql Admin Port
      - "6032:6032"
    depends_on:
      - lab4-db-node-1
      - lab4-db-node-2

  # user_service:
  #   build:
  #     context: ./services/user
  #     dockerfile: Dockerfile
  #   container_name: user_service
  #   environment:
  #     - DB_HOST=proxysql
  #     - DB_PORT=6033
  #     - DB_LOGIN=stud
  #     - DB_PASSWORD=stud
  #     - DB_DATABASE=archdb
  #     - CACHE=cache:6379
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - arch-network
  #   depends_on:
  #     - proxysql

  # lecture_service:
  #   build:
  #     context: ./services/lecture
  #     dockerfile: Dockerfile
  #   container_name: lecture_service
  #   environment:
  #     - DB_HOST=proxysql
  #     - DB_PORT=6033
  #     - DB_LOGIN=stud
  #     - DB_PASSWORD=stud
  #     - DB_DATABASE=archdb
  #     - CACHE=cache:6379
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - arch-network
  #   depends_on:
  #     - proxysql

  # conference_service:
  #   build:
  #     context: ./services/conference
  #     dockerfile: Dockerfile
  #   container_name: conference_service
  #   environment:
  #     - DB_HOST=proxysql
  #     - DB_PORT=6033
  #     - DB_LOGIN=stud
  #     - DB_PASSWORD=stud
  #     - DB_DATABASE=archdb
  #     - CACHE=cache:6379
  #   ports:
  #     - 8082:8082
  #   networks:
  #     - arch-network
  #   depends_on:
  #     - proxysql

volumes:
  lab4-db-node-1-data:
  lab4-db-node-2-data:
  lab4-proxysql-data:
  lab4-cache:

networks:
  arch-network:
    driver: "bridge"
    external: false